version: '3'

services:
#  api:
#    container_name: "posts-api"
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8081:8080
#    environment:
#      DB_USER: sa
#      DB_PASSWORD: password
#      DB_NAME: compose-db
#      DB_HOST: postgres_db
#      DB_PORT: 5432

  postgres_db:
    container_name: postgres_db_posts
    image: postgres:12
    ports:
          - 5433:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#  volumes:
#    pgdata:
#      external:true